[package]
name = "ices-example-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ices-sdk = { path= "../../../sdk" }
ic-cdk = "0.4.0"
candid = "0.7.13"
ic-cdk-macros = "0.5.0"
serde = "1.0.126"
serde_derive = "1.0.126"
